spring.application.name=truckcheckin

spring.datasource.url=jdbc:postgresql://localhost:5432/truck_checkin
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true